[string] $_URL = 'portal.manage.microsoft.com'
[string] $_URL1 = 'm.manage.microsoft.com'
[string] $_URL2 = 'sts.manage.microsoft.com'
[string] $_URL3 ='portal.fei.msua01.manage.microsoft.com'
[string] $_URL4 ='m.fei.msua01.manage.microsoft.com'
[string] $_URL5 ='portal.fei.amsua0102.manage.microsoft.com'
[string] $_URL6 ='m.fei.amsua0102.manage.microsoft.com'
[string] $_URL7 ='portal.fei.msua02.manage.microsoft.com'
[string] $_URL8 ='m.fei.msua02.manage.microsoft.com'
[string] $_URL9 ='portal.fei.msua04.manage.microsoft.com'
[string] $_URL10 ='m.fei.msua04.manage.microsoft.com'
[string] $_URL11='portal.fei.msua05.manage.microsoft.com'
[string] $_URL12 ='m.fei.msua05.manage.microsoft.com'
[string] $_URL13 ='portal.fei.amsua0502.manage.microsoft.com'
[string] $_URL14 ='m.fei.amsua0502.manage.microsoft.com'
[string] $_URL15 ='portal.fei.msua06.manage.microsoft.com'
[string] $_URL16 ='m.fei.msua06.manage.microsoft.com'
[string] $_URL17 ='portal.fei.amsua0602.manage.microsoft.com'
[string] $_URL18 ='m.fei.amsua0602.manage.microsoft.com'
[string] $_URL19 ='fei.amsua0202.manage.microsoft.com'
[string] $_URL20 ='portal.fei.amsua0202.manage.microsoft.com'
[string] $_URL21 ='m.fei.amsua0202.manage.microsoft.com'
[string] $_URL22 ='portal.fei.amsua0402.manage.microsoft.com'
[string] $_URL23 ='m.fei.amsua0402.manage.microsoft.com'
[string] $_URL24 ='portal.fei.msua07.manage.microsoft.com'
[string] $_URL25 ='portal.fei.amsua0702.manage.microsoft.com'
[string] $_URL26 ='portal.fei.amsua0801.manage.microsoft.com'
[string] $_URL27 ='portal.fei.msua08.manage.microsoft.com'
[string] $_URL28 ='m.fei.msua07.manage.microsoft.com'
[string] $_URL29 ='m.fei.amsua0702.manage.microsoft.com'
[string] $_URL30 ='m.fei.msua08.manage.microsoft.com'
[string] $_URL31 ='m.fei.amsua0801.manage.microsoft.com'
[string] $_URL32 ='portal.fei.msub01.manage.microsoft.com'
[string] $_URL33 ='m.fei.msub01.manage.microsoft.com'
[string] $_URL34 ='portal.fei.amsub0102.manage.microsoft.com'
[string] $_URL35 ='m.fei.amsub0102.manage.microsoft.com'
[string] $_URL36 ='portal.fei.msub02.manage.microsoft.com'
[string] $_URL37 ='m.fei.msub02.manage.microsoft.com'
[string] $_URL38 ='portal.fei.msub03.manage.microsoft.com'
[string] $_URL39 ='m.fei.msub03.manage.microsoft.com'
[string] $_URL40 ='portal.fei.msub05.manage.microsoft.com'
[string] $_URL41 ='m.fei.msub05.manage.microsoft.com'
[string] $_URL42 ='portal.fei.amsub0202.manage.microsoft.com'
[string] $_URL43 ='m.fei.amsub0202.manage.microsoft.com'
[string] $_URL44 ='portal.fei.amsub0302.manage.microsoft.com'
[string] $_URL45 ='m.fei.amsub0302.manage.microsoft.com'
[string] $_URL46 ='portal.fei.amsub0502.manage.microsoft.com'
[string] $_URL47 ='m.fei.amsub0502.manage.microsoft.com'
[string] $_URL48 ='portal.fei.amsub0601.manage.microsoft.com'
[string] $_URL49 ='m.fei.amsub0601.manage.microsoft.com'

[string] $_URL50 ='portal.fei.msuc01.manage.microsoft.com'
[string] $_URL51 ='m.fei.msuc01.manage.microsoft.com'
[string] $_URL52 ='portal.fei.msuc02.manage.microsoft.com'
[string] $_URL53 ='m.fei.msuc02.manage.microsoft.com'
[string] $_URL54 ='portal.fei.msuc03.manage.microsoft.com'
[string] $_URL55 ='m.fei.msuc03.manage.microsoft.com'
[string] $_URL56 ='portal.fei.msuc05.manage.microsoft.com'
[string] $_URL57 ='m.fei.msuc05.manage.microsoft.com'

[string] $_URL58 ='portal.fei.amsud0101.manage.microsoft.com'
[string] $_URL59 ='m.fei.amsud0101.manage.microsoft.com'
[string] $_URL60 ='Admin.manage.microsoft.com'
[string] $_URL61 ='fef.msuc03.manage.microsoft.com'
[string] $_URL62 ='wip.mam.manage.microsoft.com'

[string] $_URL63 ='mam.manage.microsoft.com'


$s = 0
while ($s <64) {

CheckSiteURLStatus $_URL$s
$s = $s +1
}
